service: microservicio-usuarios
org: parislht

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  memorySize: 1024
  timeout: 30
  stage: ${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::418047659300:role/LabRole
  environment:
    TABLE_NAME_USERS: ${sls:stage}-t_usuarios
    TABLE_NAME_TOKENS: ${sls:stage}-t_tokens_acceso

functions:
  crear-usuario:
    handler: src/usuarios/crear_usuario.lambda_handler
    events:
      - http:
          path: usuarios/crear
          method: post
          cors: true

  login-usuario:
    handler: src/usuarios/login_usuario.lambda_handler
    events:
      - http:
          path: usuarios/login
          method: post
          cors: true

  validarTokenAcceso:
    handler: src/usuarios/validar_token_acceso.lambda_handler

resources:
  Resources:
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_USERS}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: username
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    TokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_TOKENS}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: token
            KeyType: RANGE
        BillingMode: "PAY_PER_REQUEST"
